##
## These default app settings are injected into django.conf.settings by the
## Appconfig
## 
KARMA_MINIMUM = 10
KARMA_DEFAULT = 100
KARMA_MAXIMUM = 200
KARMA_TO_JOIN = 70
KARMA_TO_FAST = 110
KARMA_TO_PRIVATE = 110
KARMA_TO_UNLIMITED = 130
KARMA_TO_REVOLUTION = 170
SURRENDER_KARMA = -10
GAMES_LIMIT = 50
SIGNATURE_MAX_LENGTH = 1024
DEFAULT_AUTOSUBSCRIBE = True
